sudo: required
language: c++
osx_image: xcode8.2
os:
- linux
- osx

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 python3; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install numpy; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/QTDIR = $(QTDIR_$(QT_VERSION))/QTDIR = \/usr\/local\/opt\/qt5/g' xcconfig/targetReleaseNionUILauncher.xcconfig; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/PYTHONHOME = $(HOME)\/Developer\/miniconda43/PYTHONHOME = \/usr\/local\/opt\/python3\/Frameworks\/Python.framework\/Versions\/3.6/g' xcconfig/targetReleaseNionUILauncher.xcconfig; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - python3-dev

script: bash travis-build.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: # add API key here
  file: release/*
  file_glob: true
  prerelease: true
  on:
    repo: nion-software/nionui-launcher
    tags: true
